-- 코드를 입력하세요
SELECT OUTS.ANIMAL_ID, OUTS.ANIMAL_TYPE, OUTS.NAME
FROM ANIMAL_OUTS AS OUTS
LEFT JOIN ANIMAL_INS AS INS
ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
WHERE 
    (OUTS.SEX_UPON_OUTCOME LIKE 'NEUTERED%' OR OUTS.SEX_UPON_OUTCOME LIKE 'SPAYED%')
    AND 
    (INS.SEX_UPON_INTAKE NOT LIKE 'NEUTERED%' AND INS.SEX_UPON_INTAKE NOT LIKE 'SPAYED%')