-- 코드를 입력하세요
WITH RECURSIVE CTE AS (
    SELECT 0 AS HOUR #초기값 설정
    UNION ALL #위 쿼리와 아래 쿼리의 값을 연산
    SELECT HOUR + 1 FROM CTE #하나씩 불려 나감
    WHERE HOUR < 23 #반복을 멈추는 용도
)

SELECT CTE.HOUR, COUNT(HOUR(OUTS.DATETIME)) AS COUNT
FROM CTE
LEFT JOIN ANIMAL_OUTS AS OUTS
ON CTE.HOUR = HOUR(OUTS.DATETIME)
GROUP BY CTE.HOUR